name: portal_ui_core
description: Design tokens, ThemeExtension, and theme factories for the Portal UI kit.
version: 0.1.2
repository: https://github.com/tanvoid0/portal_packages/tree/main/portal_ui_core

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.11
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
